load_path: "" # only used when separately evaluating a pretrained model
eval: false
batch_size: 64
num_workers: 4
n_eval: 5 # TODO modify it to 20 when deploy
eval_every: 5
max_steps: 600
use_mp: false
num_procs: 20
save_sim_states: false
