lora_rank: 8
train_all_bias: false
adapt_demo_num_each_task: 5
#adaptation_task_id: 5
n_epochs: 50
eval_every: 10
eval: false
n_eval: 20
eval_in_train: false
exp_dir: './experiments/lora_adaptation/'
pre_trained_model_path: '../scripts/experiments/LIBERO_90/PreTrainMultitask/BCViLTPolicy_seed10000/run_006/multitask_model_ep20.pth'
seed: 100
policy_type: 'LoraBCViLTPolicy'
batch_size: 2
optim_name: torch.optim.AdamW
adaption_suite: "LIBERO_OBJECT"
adapt_all: false
adaptation_tasks: [1,3]
optim_kwargs:
    lr: 0.0003
    betas: [0.9, 0.999]
    weight_decay: 0.0001